'use client';

import { useEffect, useMemo, useState } from 'react';

const KEY='my-budget-v5';
const DEFAULT_LOAN={original:42717.24,apr:11.99,term:84,required:757.61,planned:1000,firstPayment:'2026-10-24',payments:[]};
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
const parse=s=>new Date(`${s}T12:00:00`),iso=d=>d.toISOString().slice(0,10);
function addMonths(s,n){const a=parse(s),day=a.getDate(),d=new Date(a.getFullYear(),a.getMonth()+n,1,12),last=new Date(d.getFullYear(),d.getMonth()+1,0,12).getDate();d.setDate(Math.min(day,last));return iso(d)}
function payoff(original,apr,payment){let bal=Number(original),rate=Number(apr)/1200,months=0,interest=0;while(bal>0.005&&months<600){const i=bal*rate;if(payment<=i)return null;const p=Math.min(Number(payment),bal+i);interest+=i;bal=Math.max(0,bal+i-p);months++}return{months,interest}}

export default function AutoLoanPage(){
 const[loan,setLoan]=useState(DEFAULT_LOAN),[payment,setPayment]=useState({date:'2026-10-24',amount:'1000'}),[ready,setReady]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const data=JSON.parse(raw);if(data.loan)setLoan({...DEFAULT_LOAN,...data.loan})}}catch{}setReady(true)},[]);
 useEffect(()=>{if(!ready)return;try{const raw=localStorage.getItem(KEY);const data=raw?JSON.parse(raw):{};localStorage.setItem(KEY,JSON.stringify({...data,loan}))}catch{}},[loan,ready]);
 const info=useMemo(()=>{let balance=Number(loan.original),interestPaid=0,principalPaid=0,rate=Number(loan.apr)/1200;const rows=[...(loan.payments||[])].sort((a,b)=>a.date.localeCompare(b.date)).map(p=>{const interest=balance*rate,amount=Math.min(Number(p.amount),balance+interest),principal=Math.max(0,amount-interest);balance=Math.max(0,balance-principal);interestPaid+=interest;principalPaid+=principal;return{...p,interest,principal,balance}});const required=payoff(balance,loan.apr,loan.required),planned=payoff(balance,loan.apr,loan.planned),saved=required&&planned?required.interest-planned.interest:0;return{balance,interestPaid,principalPaid,rows,required,planned,saved}},[loan]);
 function addPayment(e){e.preventDefault();if(!payment.date||!payment.amount)return;setLoan(l=>({...l,payments:[...(l.payments||[]),{id:String(Date.now()),date:payment.date,amount:Number(payment.amount)}]}));setPayment(p=>({...p,date:addMonths(p.date,1)}))}
 function remove(id){setLoan(l=>({...l,payments:(l.payments||[]).filter(p=>p.id!==id)}))}
 return <main className="shell loan-page"><header className="standalone-header"><div><p className="eyebrow">Auto loan</p><h1>Bronco Sport loan tracker</h1><p className="sub">Track payments, estimated principal, interest and payoff progress separately from your everyday budget.</p></div><a className="small-button back-link" href="/">Back to budget</a></header>
 <section className="panel"><div className="section-head"><div><h2>Loan details</h2></div><p>Estimated amortization. Actual lender payoff can vary with daily simple interest and payment timing.</p></div><div className="summary-grid"><label className="card">Original amount financed<input type="number" step=".01" value={loan.original} onChange={e=>setLoan({...loan,original:Number(e.target.value)})}/></label><label className="card">APR %<input type="number" step=".01" value={loan.apr} onChange={e=>setLoan({...loan,apr:Number(e.target.value)})}/></label><label className="card">Required payment<input type="number" step=".01" value={loan.required} onChange={e=>setLoan({...loan,required:Number(e.target.value)})}/></label><label className="card">Your planned payment<input type="number" step=".01" value={loan.planned} onChange={e=>setLoan({...loan,planned:Number(e.target.value)})}/></label></div><div className="stats"><article><span>Estimated balance</span><strong>{money(info.balance)}</strong></article><article><span>Principal paid</span><strong>{money(info.principalPaid)}</strong></article><article><span>Interest paid</span><strong>{money(info.interestPaid)}</strong></article></div><div className="stats"><article><span>At {money(loan.required)}/mo</span><strong>{info.required?`${info.required.months} months left`:'—'}</strong></article><article><span>At {money(loan.planned)}/mo</span><strong>{info.planned?`${info.planned.months} months left`:'—'}</strong></article><article><span>Est. future interest saved</span><strong>{money(info.saved)}</strong></article></div></section>
 <section className="panel"><div className="section-head"><div><h2>Payment history</h2></div></div><form className="form-grid rule-add" onSubmit={addPayment}><input type="date" value={payment.date} onChange={e=>setPayment({...payment,date:e.target.value})}/><input type="number" step=".01" placeholder="Payment amount" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/><button type="submit">Add payment</button></form>{info.rows.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Payment</th><th>Interest</th><th>Principal</th><th>Balance</th><th></th></tr></thead><tbody>{info.rows.map(r=><tr key={r.id}><td>{r.date}</td><td>{money(r.amount)}</td><td>{money(r.interest)}</td><td>{money(r.principal)}</td><td>{money(r.balance)}</td><td><button className="small-button" onClick={()=>remove(r.id)}>Delete</button></td></tr>)}</tbody></table></div>:<p className="empty">No loan payments recorded yet.</p>}</section>
 </main>;
}
