'use client';

import {useEffect,useMemo,useState} from 'react';
import CloudSync from './CloudSync';
import { House, ListChecks, CircleCheck, Shapes, Landmark, ChartNoAxesColumnIncreasing, Settings, WalletCards, Clock3, CarFront, UserRound, CreditCard, Search, ChevronLeft, ChevronRight, CircleDollarSign } from 'lucide-react';

const KEY='my-budget-v5', RECON='my-budget-reconciliation-v1', ACCOUNTS='my-budget-accounts-v1';
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
const iso=d=>d.toISOString().slice(0,10), parse=s=>new Date(s+'T12:00:00');
const addDays=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+n);return iso(d)};
const addMonths=(s,n)=>{const d=parse(s),day=d.getDate(),x=new Date(d.getFullYear(),d.getMonth()+n,1,12),last=new Date(x.getFullYear(),x.getMonth()+1,0,12).getDate();x.setDate(Math.min(day,last));return iso(x)};
const pretty=s=>parse(s).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const short=s=>parse(s).toLocaleDateString('en-US',{month:'short',day:'numeric'});
const cats=['Housing','Auto','Food','Utilities','Insurance','Child Support','Debt','Personal','Savings','Other'];
const tones={Housing:'red',Auto:'blue',Food:'orange',Utilities:'green',Insurance:'cyan','Child Support':'purple',Debt:'violet',Personal:'pink',Savings:'green',Other:'gray'};
function catFor(n='',c=''){if(c)return c.replace('Auto/Transportation','Auto').replace('Food/Household','Food').replace('Debt/Financing','Debt');n=n.toLowerCase();if(n.includes('rent'))return'Housing';if(n.includes('bronco')||n.includes('gas')||n.includes('auto'))return'Auto';if(n.includes('grocery')||n.includes('food'))return'Food';if(n.includes('phone')||n.includes('internet')||n.includes('village')||n.includes('electric'))return'Utilities';if(n.includes('support'))return'Child Support';if(n.includes('insurance'))return'Insurance';if(n.includes('zip')||n.includes('card')||n.includes('loan'))return'Debt';return'Other'}
function occ(b,start,end){let d=b.startDate||b.dueDate,out=[],g=0;if(!d)return out;while(d<start&&g++<500){if(b.repeat==='weekly')d=addDays(d,7);else if(b.repeat==='biweekly')d=addDays(d,14);else if(b.repeat==='monthly')d=addMonths(d,1);else return out}while(d<=end&&g++<1000){if(!b.endDate||d<=b.endDate)out.push({...b,date:d,key:b.id+':'+d});if(b.repeat==='weekly')d=addDays(d,7);else if(b.repeat==='biweekly')d=addDays(d,14);else if(b.repeat==='monthly')d=addMonths(d,1);else break}return out}
function payPeriod(anchor,today){let p=anchor||today,g=0;while(p>today&&g++<100)p=addDays(p,-14);while(addDays(p,14)<=today&&g++<200)p=addDays(p,14);return{start:p,end:addDays(p,13),next:addDays(p,14)}}
const blankTx={name:'',amount:'',dueDate:'',repeat:'one-time',category:'Other',actual:''};
const blankAccount={type:'auto',name:'',balance:'',apr:'',payment:'',limit:'',nextDue:''};

export default function BudgetApp(){
 const[budget,setBudget]=useState(null),[recon,setRecon]=useState({}),[accounts,setAccounts]=useState([]),[tab,setTab]=useState('home'),[filter,setFilter]=useState('all'),[editing,setEditing]=useState(null),[acctEdit,setAcctEdit]=useState(null),[actual,setActual]=useState(''),[note,setNote]=useState('');
 useEffect(()=>{try{const b=JSON.parse(localStorage.getItem(KEY)||'null');if(b)setBudget(b);setRecon(JSON.parse(localStorage.getItem(RECON)||'{}'));let a=JSON.parse(localStorage.getItem(ACCOUNTS)||'null');if(!a&&b?.loan)a=[{id:'auto-main',type:'auto',name:'Bronco Sport Loan',balance:Number(b.loan.original||0),apr:Number(b.loan.apr||0),payment:Number(b.loan.required||0),nextDue:b.loan.firstPayment||'',limit:0}];setAccounts(a||[])}catch{}},[]);
 function saveBudget(b){setBudget(b);localStorage.setItem(KEY,JSON.stringify(b));window.dispatchEvent(new CustomEvent('budget-data-change'))}
 function saveRecon(r){setRecon(r);localStorage.setItem(RECON,JSON.stringify(r))}
 function saveAccounts(a){setAccounts(a);localStorage.setItem(ACCOUNTS,JSON.stringify(a))}
 const model=useMemo(()=>{if(!budget)return null;const today=iso(new Date()),p=payPeriod(budget.payday,today),adjust=budget.adjustments||{},items=(budget.bills||[]).flatMap(b=>occ(b,p.start,p.end)).flatMap(o=>{const a=adjust[o.key]||{};if(a.deleted)return[];return[{...o,date:a.date||o.date,planned:Number(a.planned ?? o.amount ?? 0),actual:Number(a.actual||0),category:catFor(o.name,o.category)}]}).sort((a,b)=>a.date.localeCompare(b.date));let prior=Object.entries(recon).filter(([k,r])=>k<p.start&&r?.reconciled&&r.actualBalance!==''&&r.actualBalance!=null).sort(([a],[b])=>b.localeCompare(a))[0]?.[1]?.actualBalance;const carried=prior!==undefined?Number(prior):Number(budget.bank||0),income=Number(budget.paycheck||0),spent=items.reduce((s,x)=>s+x.actual,0),planned=items.reduce((s,x)=>s+x.planned,0),remainingPlanned=items.reduce((s,x)=>s+Math.max(0,x.planned-x.actual),0),available=carried+income-spent,projected=carried+income-planned;return{today,p,items,carried,income,spent,planned,remainingPlanned,available,projected}},[budget,recon]);
 if(!budget||!model)return <div className="mock-loading">Loading My Budget…</div>;
 function patchItem(item,patch){saveBudget({...budget,adjustments:{...(budget.adjustments||{}),[item.key]:{...((budget.adjustments||{})[item.key]||{}),...patch}}})}
 function removeItem(item){if(!confirm('Delete this transaction?'))return;if(item.repeat==='one-time')saveBudget({...budget,bills:budget.bills.filter(b=>b.id!==item.id)});else patchItem(item,{deleted:true})}
 function saveTx(e){e.preventDefault();const x=editing;if(!x.name||!x.amount||!x.dueDate)return;if(x.key){const bills=budget.bills.map(b=>b.id===x.id?{...b,name:x.name,category:x.category,repeat:x.repeat}:b);saveBudget({...budget,bills,adjustments:{...(budget.adjustments||{}),[x.key]:{...((budget.adjustments||{})[x.key]||{}),date:x.dueDate,planned:Number(x.amount),actual:Number(x.actual||0)}}})}else{const id='tx-'+Date.now();saveBudget({...budget,bills:[...budget.bills,{id,name:x.name,amount:Number(x.amount),dueDate:x.dueDate,startDate:x.dueDate,repeat:x.repeat,category:x.category}]})}setEditing(null)}
 function completeRecon(){if(actual==='')return;const diff=Number(actual)-model.available;saveRecon({...recon,[model.p.start]:{reconciled:true,actualBalance:Number(actual),expectedBalance:model.available,difference:diff,note,completedAt:new Date().toISOString()}});setActual('');setNote('')}
 function saveAcct(e){e.preventDefault();const x=acctEdit;if(!x.name)return;const obj={...x,id:x.id||'acct-'+Date.now(),balance:Number(x.balance||0),apr:Number(x.apr||0),payment:Number(x.payment||0),limit:Number(x.limit||0)};saveAccounts(x.id?accounts.map(a=>a.id===x.id?obj:a):[...accounts,obj]);setAcctEdit(null)}
 const upcoming=model.items.filter(x=>x.actual<x.planned).slice(0,5),days=Math.max(0,Math.ceil((parse(model.p.end)-parse(model.today))/86400000));
 const nav=[['home',House,'Home'],['transactions',ListChecks,'Transactions'],['reconciliation',CircleCheck,'Reconciliation'],['categories',Shapes,'Categories'],['accounts',Landmark,'Accounts']];
 return <div className="mock-app">
  <aside className="mock-sidebar"><div className="mock-brand"><span><CircleDollarSign size={16}/></span> My Budget</div><nav>{nav.map(([id,Icon,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><i><Icon size={17}/></i>{l}</button>)}<button onClick={()=>setTab('reports')}><i><ChartNoAxesColumnIncreasing size={17}/></i>Reports</button><button onClick={()=>setTab('settings')}><i><Settings size={17}/></i>Settings</button></nav></aside>
  <main className="mock-main">
   {tab==='home'&&<><header><div><h1>Good morning.</h1><b>Current Pay Period</b><p>{short(model.p.start)} – {short(model.p.end)}</p></div><span className="days">{days} days left</span></header>
    <section className="hero-balance"><span className="round-icon"><WalletCards size={21}/></span><div><strong>{money(model.available)}</strong><p>Available This Pay Period</p></div><div className="equation"><b>{money(model.carried)}</b><small>Carried Over</small><em>+</em><b>{money(model.income)}</b><small>Paycheck</small><em>=</em><b>{money(model.carried+model.income)}</b><small>Total Available</small></div></section>
    <div className="metric-row"><article className="m-green"><strong>{money(model.spent)}</strong><span>Spent (Actual)</span></article><article className="m-orange"><strong>{money(model.remainingPlanned)}</strong><span>Planned Remaining</span></article><article className="m-blue"><strong>{money(model.projected)}</strong><span>Projected Remaining</span></article></div>
    <div className="progress-title"><b>Pay Period Progress</b><span>{Math.round(((14-days)/14)*100)}%</span></div><div className="progress"><i style={{width:Math.max(0,Math.min(100,((14-days)/14)*100))+'%'}}/></div>
    <div className="section-title"><h2>Upcoming Bills</h2><button onClick={()=>setTab('transactions')}>See All</button></div><div className="bill-list">{upcoming.map(x=><TxRow key={x.key} x={x} onEdit={()=>setEditing({...x,amount:x.planned,dueDate:x.date})} onPaid={()=>patchItem(x,{actual:x.planned})}/>)}</div></>}
   {tab==='transactions'&&<><Top title="Transactions" action="+ Add Transaction" onAction={()=>setEditing({...blankTx,dueDate:model.today})}/><div className="segmented"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button><button className={filter==='recurring'?'active':''} onClick={()=>setFilter('recurring')}>Recurring</button><button className={filter==='one-time'?'active':''} onClick={()=>setFilter('one-time')}>One-Off</button></div><div className="search">⌕ &nbsp; Search transactions…</div><div className="tx-table"><div className="tx-head"><span>Name</span><span>Date</span><span>Planned</span><span>Actual</span><span>Status</span></div>{model.items.filter(x=>filter==='all'||(filter==='recurring'?x.repeat!=='one-time':x.repeat==='one-time')).map(x=><TxRow key={x.key} x={x} full onEdit={()=>setEditing({...x,amount:x.planned,dueDate:x.date})} onDelete={()=>removeItem(x)} onPaid={()=>patchItem(x,{actual:x.planned})}/>)}</div></>}
   {tab==='reconciliation'&&<><Top title="Weekly Reconciliation"/><div className="recon-date"><ChevronLeft size={16}/> <b>{pretty(model.p.end)}</b> <ChevronRight size={16}/></div><div className="info-card"><span className="round-icon"><Clock3 size={21}/></span><div><b>Let’s make sure everything matches</b><p>Compare your actual bank balance with the app balance. This will be the carry-over for next period.</p></div></div><div className="recon-form"><label>App Calculated Balance <strong>{money(model.available)}</strong></label><label>Your Actual Bank Balance <input type="number" step=".01" value={actual} onChange={e=>setActual(e.target.value)} placeholder={model.available.toFixed(2)}/></label><label>Difference <strong className={(Number(actual||model.available)-model.available)===0?'green':''}>{money(Number(actual||model.available)-model.available)}</strong></label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note (optional)…"/><button className="primary" onClick={completeRecon}>Complete Reconciliation</button></div>{Object.entries(recon).filter(([,r])=>r.reconciled).sort(([a],[b])=>b.localeCompare(a)).slice(0,1).map(([d,r])=><div className="last-recon" key={d}><h3>Last Reconciliation <span>✓ Matched</span></h3><p>App Balance <b>{money(r.expectedBalance)}</b></p><p>Actual Balance <b>{money(r.actualBalance)}</b></p><p>Difference <b className="green">{money(r.difference)}</b></p></div>)}</>}
   {tab==='accounts'&&<><Top title="Accounts" action="+ Add Account" onAction={()=>setAcctEdit({...blankAccount})}/><div className="segmented"><button className="active">All</button><button>Auto Loans</button><button>Personal Loans</button><button>Credit Cards</button></div><div className="account-list">{accounts.map(a=><article className="account-card" key={a.id} onClick={()=>setAcctEdit({...a})}><span className={'acct-icon '+(a.type==='card'?'orange':a.type==='personal'?'purple':'gray')}>{a.type==='card'?<CreditCard size={20}/>:a.type==='personal'?<UserRound size={20}/>:<CarFront size={20}/>}</span><div><small>{a.type==='auto'?'Auto Loan':a.type==='personal'?'Personal Loan':'Credit Card'}</small><h3>{a.name}</h3><strong>{money(a.balance)}</strong>{a.type==='card'&&a.limit>0&&<div className="util"><i style={{width:Math.min(100,a.balance/a.limit*100)+'%'}}/></div>}<p>APR <b>{a.apr}%</b> &nbsp;&nbsp; Payment <b>{money(a.payment)}</b> &nbsp;&nbsp; Next Due <b>{a.nextDue?short(a.nextDue):'—'}</b></p></div><b>›</b></article>)}</div></>}
   {tab==='categories'&&<Categories items={model.items}/>}
   {tab==='reports'&&<Categories items={model.items} title="Reports"/>}
   {tab==='settings'&&<><Top title="Settings"/><div className="settings-card"><h3>Automatic Saving</h3><p>Your budget saves automatically on this device and your existing cloud sync remains active.</p><CloudSync/></div></>}
  </main>
  <nav className="mobile-nav">{[['home',House,'Home'],['transactions',ListChecks,'Transactions'],['accounts',Landmark,'Accounts'],['categories',Shapes,'More']].map(([id,Icon,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><i><Icon size={20}/></i><span>{l}</span></button>)}</nav>
  {editing&&<Modal title={editing.key?'Edit Transaction':'Add Transaction'} close={()=>setEditing(null)}><form onSubmit={saveTx}><div className="segmented"><button type="button" className={editing.repeat!=='one-time'?'active':''} onClick={()=>setEditing({...editing,repeat:'monthly'})}>Recurring</button><button type="button" className={editing.repeat==='one-time'?'active':''} onClick={()=>setEditing({...editing,repeat:'one-time'})}>One-Off</button></div><Field label="Name"><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="Category"><select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Amount (Planned)"><input type="number" step=".01" value={editing.amount} onChange={e=>setEditing({...editing,amount:e.target.value})}/></Field><Field label="Due Date"><input type="date" value={editing.dueDate} onChange={e=>setEditing({...editing,dueDate:e.target.value})}/></Field>{editing.repeat!=='one-time'&&<Field label="Repeat"><select value={editing.repeat} onChange={e=>setEditing({...editing,repeat:e.target.value})}><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option><option value="monthly">Monthly</option></select></Field>}<Field label="Actual"><input type="number" step=".01" value={editing.actual||''} onChange={e=>setEditing({...editing,actual:e.target.value})}/></Field><button className="primary">Save</button>{editing.key&&<button type="button" className="danger" onClick={()=>{removeItem(editing);setEditing(null)}}>Delete Transaction</button>}</form></Modal>}
  {acctEdit&&<Modal title={acctEdit.id?'Edit Account':'Add Account'} close={()=>setAcctEdit(null)}><form onSubmit={saveAcct}><Field label="Account Type"><select value={acctEdit.type} onChange={e=>setAcctEdit({...acctEdit,type:e.target.value})}><option value="auto">Auto Loan</option><option value="personal">Personal Loan</option><option value="card">Credit Card</option></select></Field><Field label="Name"><input value={acctEdit.name} onChange={e=>setAcctEdit({...acctEdit,name:e.target.value})}/></Field><Field label="Balance"><input type="number" step=".01" value={acctEdit.balance} onChange={e=>setAcctEdit({...acctEdit,balance:e.target.value})}/></Field><Field label="APR %"><input type="number" step=".01" value={acctEdit.apr} onChange={e=>setAcctEdit({...acctEdit,apr:e.target.value})}/></Field><Field label="Payment"><input type="number" step=".01" value={acctEdit.payment} onChange={e=>setAcctEdit({...acctEdit,payment:e.target.value})}/></Field>{acctEdit.type==='card'&&<Field label="Credit Limit"><input type="number" step=".01" value={acctEdit.limit} onChange={e=>setAcctEdit({...acctEdit,limit:e.target.value})}/></Field>}<Field label="Next Due"><input type="date" value={acctEdit.nextDue||''} onChange={e=>setAcctEdit({...acctEdit,nextDue:e.target.value})}/></Field><button className="primary">Save Account</button>{acctEdit.id&&<button type="button" className="danger" onClick={()=>{if(confirm('Delete this account?')){saveAccounts(accounts.filter(a=>a.id!==acctEdit.id));setAcctEdit(null)}}}>Delete Account</button>}</form></Modal>}
 </div>
}
function Top({title,action,onAction}){return <div className="topline"><h1>{title}</h1>{action&&<button className="primary small" onClick={onAction}>{action}</button>}</div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Modal({title,close,children}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><button onClick={close}>‹</button><h2>{title}</h2><button onClick={close}>Done</button></div>{children}</div></div>}
function TxRow({x,full,onEdit,onDelete,onPaid}){const paid=x.actual>=x.planned&&x.planned>0,partial=x.actual>0&&!paid;return <div className={'tx-row '+(full?'full':'')} onClick={onEdit}><div className="tx-name"><span className={'dot '+(tones[x.category]||'gray')}>●</span><div><b>{x.name}</b>{!full&&<small>{x.category} · {short(x.date)}</small>}</div></div>{full&&<span>{short(x.date)}</span>}<strong>{money(x.planned)}</strong>{full&&<strong>{x.actual?money(x.actual):'—'}</strong>}<button className={'status '+(paid?'paid':partial?'partial':x.date<=iso(new Date())?'due':'upcoming')} onClick={e=>{e.stopPropagation();onPaid?.()}}>{paid?'Paid':partial?'Partial':x.date<=iso(new Date())?'Due Soon':'Upcoming'}</button>{full&&onDelete&&<button className="row-delete" onClick={e=>{e.stopPropagation();onDelete()}}>×</button>}</div>}
function Categories({items,title='Categories'}){const data=cats.map(c=>{const xs=items.filter(x=>x.category===c);return{c,planned:xs.reduce((s,x)=>s+x.planned,0),actual:xs.reduce((s,x)=>s+x.actual,0)}}).filter(x=>x.planned||x.actual);return <><Top title={title}/><div className="category-header"><select><option>This Pay Period</option></select></div><div className="category-table"><div><b>Category</b><b>Planned</b><b>Actual</b></div>{data.map(x=><div key={x.c}><span><i className={'cat-icon '+tones[x.c]}>●</i>{x.c}</span><strong>{money(x.planned)}</strong><strong>{money(x.actual)}</strong></div>)}</div></>}
