'use client';

import {useEffect,useMemo,useState} from 'react';
import CloudSync from './CloudSync';


const KEY='my-budget-v5', RECON='my-budget-reconciliation-v1', ACCOUNTS='my-budget-accounts-v1';
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
const iso=d=>d.toISOString().slice(0,10), parse=s=>new Date(s+'T12:00:00');
const addDays=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+n);return iso(d)};
const addMonths=(s,n)=>{const d=parse(s),day=d.getDate(),x=new Date(d.getFullYear(),d.getMonth()+n,1,12),last=new Date(x.getFullYear(),x.getMonth()+1,0,12).getDate();x.setDate(Math.min(day,last));return iso(x)};
const pretty=s=>parse(s).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const short=s=>parse(s).toLocaleDateString('en-US',{month:'short',day:'numeric'});
const cats=['Housing','Auto','Food','Utilities','Insurance','Child Support','Debt','Personal','Savings','Other'];
const tones={Housing:'red',Auto:'blue',Food:'orange',Utilities:'green',Insurance:'cyan','Child Support':'purple',Debt:'violet',Personal:'pink',Savings:'green',Other:'gray'};
function catFor(n='',c=''){if(c)return c.replace('Auto/Transportation','Auto').replace('Food/Household','Food').replace('Debt/Financing','Debt');n=n.toLowerCase();if(n.includes('rent'))return'Housing';if(n.includes('bronco')||n.includes('gas')||n.includes('auto'))return'Auto';if(n.includes('grocery')||n.includes('food'))return'Food';if(n.includes('phone')||n.includes('internet')||n.includes('village')||n.includes('electric'))return'Utilities';if(n.includes('support'))return'Child Support';if(n.includes('insurance'))return'Insurance';if(n.includes('zip')||n.includes('card')||n.includes('loan'))return'Debt';return'Other'}
function occ(b,start,end){let d=b.startDate||b.dueDate,out=[],g=0;if(!d)return out;while(d<start&&g++<500){if(b.repeat==='weekly')d=addDays(d,7);else if(b.repeat==='biweekly')d=addDays(d,14);else if(b.repeat==='monthly')d=addMonths(d,1);else return out}while(d<=end&&g++<1000){if(!b.endDate||d<=b.endDate)out.push({...b,date:d,key:b.id+':'+d});if(b.repeat==='weekly')d=addDays(d,7);else if(b.repeat==='biweekly')d=addDays(d,14);else if(b.repeat==='monthly')d=addMonths(d,1);else break}return out}
function weekBounds(today){const d=parse(today),back=(d.getDay()-4+7)%7,start=addDays(today,-back);return{start,end:addDays(start,6)}}
function weekItems(budget,start,end){const adjust=budget.adjustments||{};return (budget.bills||[]).flatMap(b=>occ(b,start,end)).flatMap(o=>{const a=adjust[o.key]||{};if(a.deleted)return[];return[{...o,date:a.date||o.date,planned:Number(a.planned ?? o.amount ?? 0),actual:Number(a.actual||0),category:catFor(o.name,o.category),reconciled:Boolean(a.reconciled)}]}).sort((a,b)=>a.date.localeCompare(b.date))}
function payPeriod(anchor,today){let p=anchor||today,g=0;while(p>today&&g++<100)p=addDays(p,-14);while(addDays(p,14)<=today&&g++<200)p=addDays(p,14);return{start:p,end:addDays(p,13),next:addDays(p,14)}}
function Icon({name,size=18}){const p={home:'M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3z',transactions:'M5 5h14M5 12h14M5 19h14',check:'m5 12 4 4L19 6',categories:'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z',accounts:'M3 9h18M5 9v9m5-9v9m4-9v9m5-9v9M3 21h18M12 3 3 7h18z',reports:'M5 20V10m7 10V4m7 16v-7',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM19 12l2-1-2-4-2 .5-2-2L14.5 3h-5L9 5.5l-2 2L5 7l-2 4 2 1-.1 3L3 17l3 4 2-1 2 1h4l2-1 2 1 3-4-2-2z',wallet:'M3 6h16v13H3zM3 9h18v7h-6a3 3 0 0 1 0-6h6',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zm0 4v5l3 2',car:'M5 17h14l-1-7-2-3H8l-2 3-1 7zm2 0v3m10-3v3M7 13h2m6 0h2',person:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm-7 9a7 7 0 0 1 14 0',card:'M3 6h18v12H3zM3 10h18',money:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zm2.5 6c-.5-1-1.4-1.5-2.5-1.5-1.4 0-2.5.8-2.5 2s1 1.8 2.5 2.2 2.5 1 2.5 2.3-1.1 2.5-2.7 2.5c-1.2 0-2.3-.6-2.8-1.6M12 5.5v13',left:'m15 18-6-6 6-6',right:'m9 18 6-6-6-6',menu:'M4 6h16M4 12h16M4 18h16'};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={p[name]}/></svg>}
const blankTx={name:'',amount:'',dueDate:'',repeat:'one-time',category:'Other',actual:''};
const blankAccount={type:'auto',name:'',balance:'',apr:'',payment:'',limit:'',nextDue:''};

export default function BudgetApp(){
 const[budget,setBudget]=useState(null),[recon,setRecon]=useState({}),[accounts,setAccounts]=useState([]),[tab,setTab]=useState('home'),[filter,setFilter]=useState('all'),[txWeekOffset,setTxWeekOffset]=useState(0),[txTouchStart,setTxTouchStart]=useState(null),[editing,setEditing]=useState(null),[acctEdit,setAcctEdit]=useState(null),[actual,setActual]=useState(''),[note,setNote]=useState(''),[weekOffset,setWeekOffset]=useState(0),[mobileMenu,setMobileMenu]=useState(false);
 useEffect(()=>{try{const b=JSON.parse(localStorage.getItem(KEY)||'null');if(b)setBudget(b);setRecon(JSON.parse(localStorage.getItem(RECON)||'{}'));let a=JSON.parse(localStorage.getItem(ACCOUNTS)||'null');if(!a&&b?.loan)a=[{id:'auto-main',type:'auto',name:'Bronco Sport Loan',balance:Number(b.loan.original||0),apr:Number(b.loan.apr||0),payment:Number(b.loan.required||0),nextDue:b.loan.firstPayment||'',limit:0}];setAccounts(a||[])}catch{}},[]);
 function saveBudget(b){setBudget(b);localStorage.setItem(KEY,JSON.stringify(b));window.dispatchEvent(new CustomEvent('budget-data-change'))}
 function saveRecon(r){setRecon(r);localStorage.setItem(RECON,JSON.stringify(r))}
 function saveAccounts(a){setAccounts(a);localStorage.setItem(ACCOUNTS,JSON.stringify(a))}
 const model=useMemo(()=>{if(!budget)return null;const today=iso(new Date()),p=payPeriod(budget.payday,today),adjust=budget.adjustments||{},items=(budget.bills||[]).flatMap(b=>occ(b,p.start,p.end)).flatMap(o=>{const a=adjust[o.key]||{};if(a.deleted)return[];return[{...o,date:a.date||o.date,planned:Number(a.planned ?? o.amount ?? 0),actual:Number(a.actual||0),category:catFor(o.name,o.category)}]}).sort((a,b)=>a.date.localeCompare(b.date));let prior=Object.entries(recon).filter(([k,r])=>k<p.start&&r?.reconciled&&r.actualBalance!==''&&r.actualBalance!=null).sort(([a],[b])=>b.localeCompare(a))[0]?.[1]?.actualBalance;const carried=prior!==undefined?Number(prior):Number(budget.bank||0),income=Number(budget.paycheck||0),spent=items.reduce((s,x)=>s+x.actual,0),planned=items.reduce((s,x)=>s+x.planned,0),remainingPlanned=items.reduce((s,x)=>s+Math.max(0,x.planned-x.actual),0),available=carried+income-spent,projected=carried+income-planned;return{today,p,items,carried,income,spent,planned,remainingPlanned,available,projected}},[budget,recon]);
 if(!budget||!model)return <div className="mock-bootstrap"><div className="mock-loading">Loading My Budget…</div><div className="bootstrap-sync"><p>No budget is stored in this browser yet. If this is a new or Private browser, connect your existing cloud copy below.</p><CloudSync/></div></div>;
 function patchItem(item,patch){saveBudget({...budget,adjustments:{...(budget.adjustments||{}),[item.key]:{...((budget.adjustments||{})[item.key]||{}),...patch}}})}
 function removeItem(item){if(!confirm('Delete this transaction?'))return;if(item.repeat==='one-time')saveBudget({...budget,bills:budget.bills.filter(b=>b.id!==item.id)});else patchItem(item,{deleted:true})}
 function saveTx(e){e.preventDefault();const x=editing;if(!x.name||!x.amount||!x.dueDate)return;if(x.key){const bills=budget.bills.map(b=>b.id===x.id?{...b,name:x.name,category:x.category,repeat:x.repeat}:b);saveBudget({...budget,bills,adjustments:{...(budget.adjustments||{}),[x.key]:{...((budget.adjustments||{})[x.key]||{}),date:x.dueDate,planned:Number(x.amount),actual:Number(x.actual||0)}}})}else{const id='tx-'+Date.now();saveBudget({...budget,bills:[...budget.bills,{id,name:x.name,amount:Number(x.amount),dueDate:x.dueDate,startDate:x.dueDate,repeat:x.repeat,category:x.category}]})}setEditing(null)}
 function completeRecon(){if(actual==='')return;const diff=Number(actual)-model.available;saveRecon({...recon,[model.p.start]:{reconciled:true,actualBalance:Number(actual),expectedBalance:model.available,difference:diff,note,completedAt:new Date().toISOString()}});setActual('');setNote('')}
 function saveAcct(e){e.preventDefault();const x=acctEdit;if(!x.name)return;const obj={...x,id:x.id||'acct-'+Date.now(),balance:Number(x.balance||0),apr:Number(x.apr||0),payment:Number(x.payment||0),limit:Number(x.limit||0)};saveAccounts(x.id?accounts.map(a=>a.id===x.id?obj:a):[...accounts,obj]);setAcctEdit(null)}
 const weekTarget=addDays(model.today,weekOffset*7),reconWeek=weekBounds(weekTarget),reconItems=weekItems(budget,reconWeek.start,reconWeek.end);
 const txWeekTarget=addDays(model.today,txWeekOffset*7),txWeek=weekBounds(txWeekTarget),txWeekItems=weekItems(budget,txWeek.start,txWeek.end).filter(x=>filter==='all'||(filter==='recurring'?x.repeat!=='one-time':x.repeat==='one-time'));
 function txSwipeStart(e){setTxTouchStart(e.touches?.[0]?.clientX??null)}
 function txSwipeEnd(e){if(txTouchStart==null)return;const end=e.changedTouches?.[0]?.clientX??txTouchStart,delta=end-txTouchStart;if(Math.abs(delta)>45)setTxWeekOffset(v=>v+(delta<0?1:-1));setTxTouchStart(null)}
 function reconcileTransaction(item){const entered=prompt('Actual amount for '+item.name,String(item.actual||item.planned||''));if(entered===null)return;const n=Number(entered);if(!Number.isFinite(n)||n<0){alert('Enter a valid amount.');return}patchItem(item,{actual:n,reconciled:true,reconciledAt:new Date().toISOString()})}
 const upcoming=model.items.filter(x=>x.actual<x.planned).slice(0,5),days=Math.max(0,Math.ceil((parse(model.p.end)-parse(model.today))/86400000));
 const nav=[['home','home','Home'],['transactions','transactions','Transactions'],['reconciliation','check','Reconciliation'],['categories','categories','Categories'],['accounts','accounts','Accounts']];
 return <div className="mock-app">
  <aside className="mock-sidebar"><div className="mock-brand"><span><Icon name="money" size={16}/></span> My Budget</div><nav>{nav.map(([id,icon,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><i><Icon name={icon} size={17}/></i>{l}</button>)}<button onClick={()=>setTab('reports')}><i><Icon name="reports" size={17}/></i>Reports</button><button onClick={()=>setTab('settings')}><i><Icon name="settings" size={17}/></i>Settings</button></nav></aside>
  <main className="mock-main">
   {tab==='home'&&<><header><div><h1>Good morning.</h1><b>Current Pay Period</b><p>{short(model.p.start)} – {short(model.p.end)}</p></div><span className="days">{days} days left</span></header>
    <section className="hero-balance"><span className="round-icon"><Icon name="wallet" size={21}/></span><div><strong>{money(model.available)}</strong><p>Available This Pay Period</p></div><div className="equation"><b>{money(model.carried)}</b><small>Carried Over</small><em>+</em><b>{money(model.income)}</b><small>Paycheck</small><em>=</em><b>{money(model.carried+model.income)}</b><small>Total Available</small></div></section>
    <div className="metric-row"><article className="m-green"><strong>{money(model.spent)}</strong><span>Spent (Actual)</span></article><article className="m-orange"><strong>{money(model.remainingPlanned)}</strong><span>Planned Remaining</span></article><article className="m-blue"><strong>{money(model.projected)}</strong><span>Projected Remaining</span></article></div>
    <div className="progress-title"><b>Pay Period Progress</b><span>{Math.round(((14-days)/14)*100)}%</span></div><div className="progress"><i style={{width:Math.max(0,Math.min(100,((14-days)/14)*100))+'%'}}/></div>
    <div className="section-title"><h2>Upcoming Bills</h2><button onClick={()=>setTab('transactions')}>See All</button></div><div className="bill-list">{upcoming.map(x=><TxRow key={x.key} x={x} onEdit={()=>setEditing({...x,amount:x.planned,dueDate:x.date})} onPaid={()=>patchItem(x,{actual:x.planned})}/>)}</div></>}
   {tab==='transactions'&&<><Top title="Transactions" action="+ Add Transaction" onAction={()=>setEditing({...blankTx,dueDate:model.today})}/><div className="segmented"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button><button className={filter==='recurring'?'active':''} onClick={()=>setFilter('recurring')}>Recurring</button><button className={filter==='one-time'?'active':''} onClick={()=>setFilter('one-time')}>One-Off</button></div><section className="tx-week-view" onTouchStart={txSwipeStart} onTouchEnd={txSwipeEnd}><div className="tx-week-nav"><button onClick={()=>setTxWeekOffset(v=>v-1)} aria-label="Previous week"><Icon name="left" size={17}/></button><div><b>{txWeekOffset===0?'This Week':txWeekOffset===-1?'Last Week':txWeekOffset===1?'Next Week':'Week'}</b><span>{short(txWeek.start)} – {short(txWeek.end)}</span></div><button onClick={()=>setTxWeekOffset(v=>v+1)} aria-label="Next week"><Icon name="right" size={17}/></button></div><div className="tx-swipe-hint">Swipe left or right to change weeks</div><div className="tx-table"><div className="tx-head"><span>Name</span><span>Date</span><span>Planned</span><span>Actual</span><span>Status</span></div>{txWeekItems.length?txWeekItems.map(x=><TxRow key={x.key} x={x} full onEdit={()=>setEditing({...x,amount:x.planned,dueDate:x.date})} onDelete={()=>removeItem(x)} onPaid={()=>patchItem(x,{actual:x.planned})}/>):<div className="tx-week-empty">No transactions due this week.</div>}</div></section></>}
   {tab==='reconciliation'&&<><Top title="Weekly Reconciliation"/><div className="recon-date"><button className="week-arrow" onClick={()=>setWeekOffset(weekOffset-1)}><Icon name="left" size={16}/></button><b>{short(reconWeek.start)} – {short(reconWeek.end)}</b><button className="week-arrow" onClick={()=>setWeekOffset(weekOffset+1)}><Icon name="right" size={16}/></button></div><div className="info-card"><span className="round-icon"><Icon name="clock" size={21}/></span><div><b>Reconcile this week’s transactions</b><p>Confirm each transaction individually. Enter the actual amount paid, then finish the week by matching your bank balance.</p></div></div><div className="weekly-reconcile-list"><div className="wr-head"><span>Transaction</span><span>Due</span><span>Planned</span><span>Actual</span><span>Status</span></div>{reconItems.length?reconItems.map(x=><div className="wr-row" key={x.key}><div><b>{x.name}</b><small>{x.category}</small></div><span>{short(x.date)}</span><strong>{money(x.planned)}</strong><strong>{x.reconciled?money(x.actual):'—'}</strong><button className={'status '+(x.reconciled?'paid':'upcoming')} onClick={()=>reconcileTransaction(x)}>{x.reconciled?'✓ Reconciled':'Reconcile'}</button></div>):<p className="empty-week">No transactions due this week.</p>}</div><div className="recon-form"><h3>Finish Week</h3><label>App Calculated Balance <strong>{money(model.available)}</strong></label><label>Your Actual Bank Balance <input type="number" step=".01" value={actual} onChange={e=>setActual(e.target.value)} placeholder={model.available.toFixed(2)}/></label><label>Difference <strong className={(Number(actual||model.available)-model.available)===0?'green':''}>{money(Number(actual||model.available)-model.available)}</strong></label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note (optional)…"/><button className="primary" onClick={completeRecon}>Complete Reconciliation</button></div>{Object.entries(recon).filter(([,r])=>r.reconciled).sort(([a],[b])=>b.localeCompare(a)).slice(0,1).map(([d,r])=><div className="last-recon" key={d}><h3>Last Reconciliation <span>✓ Matched</span></h3><p>App Balance <b>{money(r.expectedBalance)}</b></p><p>Actual Balance <b>{money(r.actualBalance)}</b></p><p>Difference <b className="green">{money(r.difference)}</b></p></div>)}</>}
   {tab==='accounts'&&<><Top title="Accounts" action="+ Add Account" onAction={()=>setAcctEdit({...blankAccount})}/><div className="segmented"><button className="active">All</button><button>Auto Loans</button><button>Personal Loans</button><button>Credit Cards</button></div><div className="account-list">{accounts.map(a=><article className="account-card" key={a.id} onClick={()=>setAcctEdit({...a})}><span className={'acct-icon '+(a.type==='card'?'orange':a.type==='personal'?'purple':'gray')}>{a.type==='card'?<Icon name="card" size={20}/>:a.type==='personal'?<Icon name="person" size={20}/>:<Icon name="car" size={20}/>}</span><div><small>{a.type==='auto'?'Auto Loan':a.type==='personal'?'Personal Loan':'Credit Card'}</small><h3>{a.name}</h3><strong>{money(a.balance)}</strong>{a.type==='card'&&a.limit>0&&<div className="util"><i style={{width:Math.min(100,a.balance/a.limit*100)+'%'}}/></div>}<p>APR <b>{a.apr}%</b> &nbsp;&nbsp; Payment <b>{money(a.payment)}</b> &nbsp;&nbsp; Next Due <b>{a.nextDue?short(a.nextDue):'—'}</b></p></div><b>›</b></article>)}</div></>}
   {tab==='categories'&&<Categories items={model.items}/>}
   {tab==='reports'&&<Categories items={model.items} title="Reports"/>}
   {tab==='settings'&&<><Top title="Settings"/><div className="settings-card"><h3>Automatic Saving</h3><p>Your budget saves automatically on this device and your existing cloud sync remains active.</p><CloudSync/></div></>}
  </main>
  <nav className="mobile-nav mobile-nav-primary">{[['home','home','Home'],['transactions','transactions','Transactions'],['reconciliation','check','Reconcile']].map(([id,icon,l])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMobileMenu(false)}}><i><Icon name={icon} size={20}/></i><span>{l}</span></button>)}<button className={['accounts','categories','reports','settings'].includes(tab)?'active':''} onClick={()=>setMobileMenu(v=>!v)}><i><Icon name="menu" size={20}/></i><span>Menu</span></button></nav>{mobileMenu&&<div className="mobile-menu-sheet" onClick={()=>setMobileMenu(false)}><div className="mobile-menu-card" onClick={e=>e.stopPropagation()}><div className="mobile-menu-head"><b>Menu</b><button onClick={()=>setMobileMenu(false)}>×</button></div>{[['accounts','accounts','Accounts'],['categories','categories','Categories'],['reports','reports','Reports'],['settings','settings','Settings']].map(([id,icon,l])=><button key={id} onClick={()=>{setTab(id);setMobileMenu(false)}}><i><Icon name={icon} size={19}/></i><span>{l}</span><b>›</b></button>)}</div></div>}
  {editing&&<Modal title={editing.key?'Edit Transaction':'Add Transaction'} close={()=>setEditing(null)}><form onSubmit={saveTx}><div className="segmented"><button type="button" className={editing.repeat!=='one-time'?'active':''} onClick={()=>setEditing({...editing,repeat:'monthly'})}>Recurring</button><button type="button" className={editing.repeat==='one-time'?'active':''} onClick={()=>setEditing({...editing,repeat:'one-time'})}>One-Off</button></div><Field label="Name"><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Field><Field label="Category"><select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Amount (Planned)"><input type="number" step=".01" value={editing.amount} onChange={e=>setEditing({...editing,amount:e.target.value})}/></Field><Field label="Due Date"><input type="date" value={editing.dueDate} onChange={e=>setEditing({...editing,dueDate:e.target.value})}/></Field>{editing.repeat!=='one-time'&&<Field label="Repeat"><select value={editing.repeat} onChange={e=>setEditing({...editing,repeat:e.target.value})}><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option><option value="monthly">Monthly</option></select></Field>}<Field label="Actual"><input type="number" step=".01" value={editing.actual||''} onChange={e=>setEditing({...editing,actual:e.target.value})}/></Field><button className="primary">Save</button>{editing.key&&<button type="button" className="danger" onClick={()=>{removeItem(editing);setEditing(null)}}>Delete Transaction</button>}</form></Modal>}
  {acctEdit&&<Modal title={acctEdit.id?'Edit Account':'Add Account'} close={()=>setAcctEdit(null)}><form onSubmit={saveAcct}><Field label="Account Type"><select value={acctEdit.type} onChange={e=>setAcctEdit({...acctEdit,type:e.target.value})}><option value="auto">Auto Loan</option><option value="personal">Personal Loan</option><option value="card">Credit Card</option></select></Field><Field label="Name"><input value={acctEdit.name} onChange={e=>setAcctEdit({...acctEdit,name:e.target.value})}/></Field><Field label="Balance"><input type="number" step=".01" value={acctEdit.balance} onChange={e=>setAcctEdit({...acctEdit,balance:e.target.value})}/></Field><Field label="APR %"><input type="number" step=".01" value={acctEdit.apr} onChange={e=>setAcctEdit({...acctEdit,apr:e.target.value})}/></Field><Field label="Payment"><input type="number" step=".01" value={acctEdit.payment} onChange={e=>setAcctEdit({...acctEdit,payment:e.target.value})}/></Field>{acctEdit.type==='card'&&<Field label="Credit Limit"><input type="number" step=".01" value={acctEdit.limit} onChange={e=>setAcctEdit({...acctEdit,limit:e.target.value})}/></Field>}<Field label="Next Due"><input type="date" value={acctEdit.nextDue||''} onChange={e=>setAcctEdit({...acctEdit,nextDue:e.target.value})}/></Field><button className="primary">Save Account</button>{acctEdit.id&&<button type="button" className="danger" onClick={()=>{if(confirm('Delete this account?')){saveAccounts(accounts.filter(a=>a.id!==acctEdit.id));setAcctEdit(null)}}}>Delete Account</button>}</form></Modal>}
 </div>
}
function Top({title,action,onAction}){return <div className="topline"><h1>{title}</h1>{action&&<button className="primary small" onClick={onAction}>{action}</button>}</div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Modal({title,close,children}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><button onClick={close}>‹</button><h2>{title}</h2><button onClick={close}>Done</button></div>{children}</div></div>}
function TxRow({x,full,onEdit,onDelete,onPaid}){const paid=x.actual>=x.planned&&x.planned>0,partial=x.actual>0&&!paid;return <div className={'tx-row '+(full?'full':'')} onClick={onEdit}><div className="tx-name"><span className={'dot '+(tones[x.category]||'gray')}>●</span><div><b>{x.name}</b>{!full&&<small>{x.category} · Due {short(x.date)}</small>}</div></div>{full&&<span>{short(x.date)}</span>}<strong>{money(x.planned)}</strong>{full&&<strong>{x.actual?money(x.actual):'—'}</strong>}<button className={'status '+(paid?'paid':partial?'partial':x.date<=iso(new Date())?'due':'upcoming')} onClick={e=>{e.stopPropagation();onPaid?.()}}>{paid?'Paid':partial?'Partial':x.date<=iso(new Date())?'Due Soon':'Upcoming'}</button>{full&&onDelete&&<button className="row-delete" onClick={e=>{e.stopPropagation();onDelete()}}>×</button>}</div>}
function Categories({items,title='Categories'}){const data=cats.map(c=>{const xs=items.filter(x=>x.category===c);return{c,planned:xs.reduce((s,x)=>s+x.planned,0),actual:xs.reduce((s,x)=>s+x.actual,0)}}).filter(x=>x.planned||x.actual);return <><Top title={title}/><div className="category-header"><select><option>This Pay Period</option></select></div><div className="category-table"><div><b>Category</b><b>Planned</b><b>Actual</b></div>{data.map(x=><div key={x.c}><span><i className={'cat-icon '+tones[x.c]}>●</i>{x.c}</span><strong>{money(x.planned)}</strong><strong>{money(x.actual)}</strong></div>)}</div></>}
