'use client';

import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';

const KEY='my-budget-v5';
const parse=s=>new Date(`${s}T12:00:00`);
const iso=d=>d.toISOString().slice(0,10);
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
function addDays(s,n){const d=parse(s);d.setDate(d.getDate()+n);return iso(d)}
function addMonths(s,n){const a=parse(s),day=a.getDate(),d=new Date(a.getFullYear(),a.getMonth()+n,1,12),last=new Date(d.getFullYear(),d.getMonth()+1,0,12).getDate();d.setDate(Math.min(day,last));return iso(d)}
function monthBounds(m){const[y,mo]=m.split('-').map(Number);return{start:`${m}-01`,end:iso(new Date(y,mo,0,12))}}
function fullWeekBounds(m){const b=monthBounds(m),sd=parse(b.start),ed=parse(b.end),start=addDays(b.start,-((sd.getDay()+6)%7)),end=addDays(b.end,6-((ed.getDay()+6)%7));return{...b,weekStart:start,weekEnd:end}}
function occurrences(b,start,end){let date=b.startDate||b.dueDate,out=[],guard=0,stop=b.endDate||null;if(!date||stop&&date>stop)return[];while(date<start&&guard++<1000){if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else return[]}while(date<=end&&(!stop||date<=stop)&&guard++<2000){if(date>=start)out.push({...b,date,key:`${b.id}:${date}`});if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else break}return out}
function inferCategory(name=''){const n=name.toLowerCase();if(n.includes('rent'))return'Housing';if(n.includes('bronco')||n.includes('gas')||n.includes('auto'))return'Auto/Transportation';if(n.includes('grocery')||n.includes('household'))return'Food/Household';if(n.includes('internet')||n.includes('phone')||n.includes('spectrum')||n.includes('village'))return'Utilities';if(n.includes('child support')||n.includes('support'))return'Child Support';if(n.includes('zip')||n.includes('advance'))return'Debt/Financing';if(n.includes('insurance')||n.includes('geico'))return'Insurance';if(n.includes('tax'))return'Taxes';return'Other'}
function summarize(items){const map={};for(const i of items){const c=i.category||inferCategory(i.name),a=Number(i.planned||0),actual=Number(i.actual||0);if(!map[c])map[c]={category:c,planned:0,actual:0};map[c].planned+=a;map[c].actual+=actual}return Object.values(map).sort((a,b)=>b.planned-a.planned)}

export default function CategoryTotals(){
 const[budget,setBudget]=useState(null),[month,setMonth]=useState('2026-09'),[period,setPeriod]=useState('monthly'),[weekStart,setWeekStart]=useState(''),[target,setTarget]=useState(null);
 useEffect(()=>{function sync(){try{const raw=localStorage.getItem(KEY);if(raw)setBudget(JSON.parse(raw))}catch{}const input=document.querySelector('.month-nav input[type="month"]');if(input?.value)setMonth(input.value);setTarget(document.getElementById('category-totals-slot'))}sync();const id=setInterval(sync,750);return()=>clearInterval(id)},[]);
 const report=useMemo(()=>{if(!budget)return{rows:[],weeks:[]};const adj=budget.adjustments||{},bounds=fullWeekBounds(month),weeks=[];for(let d=bounds.weekStart;d<=bounds.weekEnd;d=addDays(d,7))weeks.push({start:d,end:addDays(d,6)});let start,end;if(period==='weekly'){const chosen=weekStart||weeks[0]?.start;start=chosen;end=addDays(chosen,6)}else if(period==='annual'){const y=month.slice(0,4);start=`${y}-01-01`;end=`${y}-12-31`}else{const b=monthBounds(month);start=b.start;end=b.end}const items=(budget.bills||[]).flatMap(b=>occurrences(b,start,end)).flatMap(o=>{const a=adj[o.key]||{};if(a.deleted)return[];const date=a.date||o.date;if(date<start||date>end)return[];return[{...o,date,category:o.category||inferCategory(o.name),planned:Number(a.planned??o.amount),actual:Number(a.actual||0)}]});return{rows:summarize(items),weeks}},[budget,month,period,weekStart]);
 useEffect(()=>{if(report.weeks.length&&!report.weeks.some(w=>w.start===weekStart))setWeekStart(report.weeks[0].start)},[report.weeks,weekStart]);
 if(!budget||!target)return null;
 const title=period==='annual'?`${month.slice(0,4)} annual totals`:period==='weekly'?'Weekly totals':`${new Date(`${month}-01T12:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'})} totals`;
 const view=<section className="panel category-panel section-accent-purple"><div className="section-head"><div><p className="eyebrow">Spending by category</p><h2>{title}</h2></div><div className="month-nav period-tabs"><button className={period==='weekly'?'active':''} type="button" onClick={()=>setPeriod('weekly')}>Weekly</button><button className={period==='monthly'?'active':''} type="button" onClick={()=>setPeriod('monthly')}>Monthly</button><button className={period==='annual'?'active':''} type="button" onClick={()=>setPeriod('annual')}>Annually</button></div></div>{period==='weekly'&&<div className="form-grid rule-add"><label>Week<select value={weekStart} onChange={e=>setWeekStart(e.target.value)}>{report.weeks.map(w=><option key={w.start} value={w.start}>{new Date(`${w.start}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})} – {new Date(`${w.end}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</option>)}</select></label></div>}<div className="category-cards">{report.rows.length?report.rows.map((r,i)=><article className={`category-total category-tone-${i%6}`} key={r.category}><span>{r.category}</span><strong>{money(r.planned)}</strong><small>{money(r.actual)} paid</small></article>):<p className="empty">No categorized expenses in this period.</p>}</div><div className="category-total-line"><span>Total planned <b>{money(report.rows.reduce((s,r)=>s+r.planned,0))}</b></span><span>Actually paid <b>{money(report.rows.reduce((s,r)=>s+r.actual,0))}</b></span></div></section>;
 return createPortal(view,target);
}
