'use client';

import { useEffect, useMemo, useState } from 'react';

const KEY='my-budget-v5';
const RECON_KEY='my-budget-reconciliation-v1';
const parse=s=>new Date(`${s}T12:00:00`),iso=d=>d.toISOString().slice(0,10);
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
const pretty=s=>parse(s).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});
function addDays(s,n){const d=parse(s);d.setDate(d.getDate()+n);return iso(d)}
function addMonths(s,n){const a=parse(s),day=a.getDate(),d=new Date(a.getFullYear(),a.getMonth()+n,1,12),last=new Date(d.getFullYear(),d.getMonth()+1,0,12).getDate();d.setDate(Math.min(day,last));return iso(d)}
function occurrences(b,start,end){let date=b.startDate||b.dueDate,out=[],guard=0,stop=b.endDate||null;if(!date||stop&&date>stop)return[];while(date<start&&guard++<1000){if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else return[]}while(date<=end&&(!stop||date<=stop)&&guard++<2000){if(date>=start)out.push({...b,date,key:`${b.id}:${date}`});if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else break}return out}
function paydayOnOrAfter(anchor,today){if(!anchor)return today;let d=anchor,guard=0;while(d<today&&guard++<1000)d=addDays(d,14);return d}
function paydayAfter(anchor,today){let d=paydayOnOrAfter(anchor,today);if(d===today)d=addDays(d,14);return d}
function latestReconciledBalance(recon,today){return Object.entries(recon||{}).filter(([start,r])=>start<today&&r?.reconciled&&r.actualBalance!==''&&r.actualBalance!==undefined).sort(([a],[b])=>b.localeCompare(a))[0]?.[1]?.actualBalance}

export default function PaycheckDashboard(){
 const[budget,setBudget]=useState(null),[recon,setRecon]=useState({});
 useEffect(()=>{function load(){try{const raw=localStorage.getItem(KEY);if(raw){const next=JSON.parse(raw);setBudget(prev=>JSON.stringify(prev)===JSON.stringify(next)?prev:next)}const rr=localStorage.getItem(RECON_KEY);setRecon(rr?JSON.parse(rr):{})}catch{}}load();const id=setInterval(load,600);window.addEventListener('budget-data-change',load);return()=>{clearInterval(id);window.removeEventListener('budget-data-change',load)}},[]);
 const view=useMemo(()=>{if(!budget)return null;const today=iso(new Date()),currentPayday=paydayOnOrAfter(budget.payday,today),isPayday=currentPayday===today,nextPayday=paydayAfter(budget.payday,today),end=addDays(nextPayday,45),adj=budget.adjustments||{};const items=(budget.bills||[]).flatMap(b=>occurrences(b,today,end)).flatMap(o=>{const a=adj[o.key]||{};if(a.deleted)return[];const date=a.date||o.date;return[{...o,date,planned:Number(a.planned??o.amount),actual:Number(a.actual||0),paid:Number(a.actual||0)>0}]}).sort((a,b)=>a.date.localeCompare(b.date));const before=items.filter(i=>i.date<nextPayday),unpaidBefore=before.filter(i=>!i.paid),due=unpaidBefore.reduce((s,i)=>s+i.planned,0),reconciled=latestReconciledBalance(recon,today),bank=reconciled!==undefined?Number(reconciled):Number(budget.bank||0),paycheck=isPayday?Number(budget.paycheck||0):0,advances=Number(budget.advances||0),startingCash=bank+paycheck,available=startingCash-advances-due;return{today,nextPayday,items,before,unpaidBefore,due,bank,paycheckToday:paycheck,scheduledPaycheck:Number(budget.paycheck||0),advances,startingCash,available,isPayday}},[budget,recon]);
 function mark(item,actual){if(!budget)return;const next={...budget,adjustments:{...(budget.adjustments||{}),[item.key]:{...((budget.adjustments||{})[item.key]||{}),actual}}};localStorage.setItem(KEY,JSON.stringify(next));setBudget(next);window.dispatchEvent(new CustomEvent('budget-data-change'))}
 if(!view)return null;
 return <section className="command-center" id="dashboard"><div className="dashboard-top"><div><p className="eyebrow">Paycheck command center</p><h1>My Budget</h1><p className="dashboard-question">How much money do I actually have available until I get paid again?</p></div><div className={`available-card ${view.available<0?'negative':''}`}><span>Available until next payday</span><strong>{money(view.available)}</strong><small>Starting cash − advances − unpaid bills before payday</small></div></div><div className="paycycle-grid"><article><span>Starting bank</span><strong>{money(view.bank)}</strong><small>{view.paycheckToday?`+ ${money(view.paycheckToday)} payday income`:''}</small></article><article><span>Cash after today's income</span><strong>{money(view.startingCash)}</strong><small>{view.isPayday?'Payday included':'No paycheck today'}</small></article><article><span>Next payday</span><strong>{pretty(view.nextPayday)}</strong><small>{money(view.scheduledPaycheck)} expected</small></article><article><span>Bills before payday</span><strong>{money(view.due)}</strong><small>{view.unpaidBefore.length} unpaid</small></article></div><div className="dashboard-columns"><div className="dash-list"><div className="compact-head"><div><p className="eyebrow">Current pay period</p><h2>Due before {pretty(view.nextPayday)}</h2></div></div>{view.before.length?view.before.map(item=><div className={`bill-row ${item.paid?'paid':''}`} key={item.key}><div><strong>{item.name}</strong><small>{pretty(item.date)} · {item.repeat==='one-time'?'One-time':item.repeat}</small></div><div className="bill-row-actions"><b>{money(item.planned)}</b><button type="button" className={item.paid?'status-button paid':'status-button'} onClick={()=>mark(item,item.paid?0:item.planned)}>{item.paid?'Paid ✓':'Mark paid'}</button></div></div>):<p className="empty compact-empty">No bills due before the next paycheck.</p>}</div><div className="dash-list"><div className="compact-head"><div><p className="eyebrow">Looking ahead</p><h2>Upcoming bills</h2></div></div>{view.items.filter(i=>i.date>=view.nextPayday).slice(0,8).map(item=><div className={`bill-row ${item.paid?'paid':''}`} key={item.key}><div><strong>{item.name}</strong><small>{pretty(item.date)} · {item.repeat==='one-time'?'One-time':item.repeat}</small></div><div className="bill-row-actions"><b>{money(item.planned)}</b>{item.paid&&<span className="paid-label">Paid</span>}</div></div>)}</div></div></section>;
}
