'use client';

import { useEffect, useMemo, useState } from 'react';

const BUDGET_KEY='my-budget-v5',RECON_KEY='my-budget-reconciliation-v1',VIEW_KEY='my-budget-week-view-v1';
const parse=s=>new Date(`${s}T12:00:00`),iso=d=>d.toISOString().slice(0,10),money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
function addDays(s,n){const d=parse(s);d.setDate(d.getDate()+n);return iso(d)}
function addMonths(s,n){const a=parse(s),day=a.getDate(),d=new Date(a.getFullYear(),a.getMonth()+n,1,12),last=new Date(d.getFullYear(),d.getMonth()+1,0,12).getDate();d.setDate(Math.min(day,last));return iso(d)}
function pretty(s){return parse(s).toLocaleDateString('en-US',{month:'short',day:'numeric'})}
function occurrences(b,start,end){let date=b.startDate||b.dueDate,out=[],guard=0,stop=b.endDate||null;if(!date||stop&&date>stop)return[];while(date<start&&guard++<500){if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else return[]}while(date<=end&&(!stop||date<=stop)&&guard++<1000){if(date>=start)out.push({...b,date,key:`${b.id}:${date}`});if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else break}return out}
function weekStartFor(date){const d=parse(date),back=(d.getDay()-4+7)%7;return addDays(date,-back)}
function monthBounds(m){const[y,mo]=m.split('-').map(Number);return{start:`${m}-01`,end:iso(new Date(y,mo,0,12))}}
function inferCategory(name=''){const n=name.toLowerCase();if(n.includes('rent'))return'Housing';if(n.includes('bronco')||n.includes('gas')||n.includes('auto'))return'Auto/Transportation';if(n.includes('grocery')||n.includes('household'))return'Food/Household';if(n.includes('internet')||n.includes('phone')||n.includes('spectrum')||n.includes('village'))return'Utilities';if(n.includes('support'))return'Child Support';if(n.includes('zip')||n.includes('advance'))return'Debt/Financing';if(n.includes('insurance')||n.includes('geico'))return'Insurance';if(n.includes('tax'))return'Taxes';return'Other'}
export default function WeekViewController(){
 const[mode,setMode]=useState('payday'),[budget,setBudget]=useState(null),[recon,setRecon]=useState({}),[month,setMonth]=useState('2026-09');
 function load(){try{const raw=localStorage.getItem(BUDGET_KEY);if(raw)setBudget(JSON.parse(raw));const rr=localStorage.getItem(RECON_KEY);setRecon(rr?JSON.parse(rr):{});const input=document.querySelector('.month-nav input[type="month"]');if(input?.value)setMonth(input.value)}catch{}}
 useEffect(()=>{setMode(localStorage.getItem(VIEW_KEY)||'payday');const view=e=>setMode(e.detail||localStorage.getItem(VIEW_KEY)||'payday');window.addEventListener('budget-week-view-change',view);return()=>window.removeEventListener('budget-week-view-change',view)},[]);
 useEffect(()=>{load();const id=setInterval(load,750);window.addEventListener('budget-data-change',load);return()=>{clearInterval(id);window.removeEventListener('budget-data-change',load)}},[]);
 useEffect(()=>{const original=document.querySelector('.details-wrap .weeks');if(original)original.classList.toggle('week-view-hidden',mode==='payday');return()=>original?.classList.remove('week-view-hidden')},[mode,budget,month]);
 const weeks=useMemo(()=>{if(!budget||mode!=='payday')return[];const bounds=monthBounds(month),start=weekStartFor(bounds.start),lastStart=weekStartFor(bounds.end),end=addDays(lastStart,6),count=Math.round((parse(end)-parse(start))/86400000/7)+1,out=Array.from({length:count},(_,i)=>({start:addDays(start,i*7),end:addDays(start,i*7+6),items:[],income:0}));for(const o of (budget.bills||[]).flatMap(b=>occurrences(b,start,end))){const a=(budget.adjustments||{})[o.key]||{};if(a.deleted)continue;const date=a.date||o.date,idx=Math.floor((parse(date)-parse(start))/86400000/7);if(out[idx])out[idx].items.push({...o,date,category:o.category||inferCategory(o.name),planned:Number(a.planned??o.amount),actual:Number(a.actual??0)})}let pd=budget.payday,guard=0;while(pd&&pd<start&&guard++<100)pd=addDays(pd,14);while(pd&&pd<=end&&guard++<200){const idx=Math.floor((parse(pd)-parse(start))/86400000/7);if(out[idx])out[idx].income+=Number(budget.paycheck||0);pd=addDays(pd,14)}out.forEach(w=>w.items.sort((a,b)=>a.date.localeCompare(b.date)));
 // A reconciliation is an authoritative closing balance. Seed the displayed range from the
 // most recent reconciliation before it when possible, then let each week's ending feed the next.
 const prior=Object.entries(recon).filter(([k,r])=>k<start&&r?.reconciled&&r.actualBalance!==''&&r.actualBalance!==undefined).sort(([a],[b])=>b.localeCompare(a))[0];let carry=prior?Number(prior[1].actualBalance):Number(budget.bank||0);
 return out.map(w=>{const r=recon[w.start]||{},planned=w.items.reduce((s,x)=>s+x.planned,0),paid=w.items.reduce((s,x)=>s+x.actual,0),extras=(r.transactions||[]).reduce((s,t)=>s+Number(t.amount||0),0),available=carry+w.income,projected=available-planned+extras,actualFlow=available-paid+extras,ending=r.reconciled&&r.actualBalance!==''&&r.actualBalance!==undefined?Number(r.actualBalance):projected,row={...w,starting:carry,available,planned,paid,extras,projected,actualFlow,ending,reconciliation:r};carry=ending;return row})},[budget,recon,month,mode]);
 function save(next){localStorage.setItem(BUDGET_KEY,JSON.stringify(next));setBudget(next);window.dispatchEvent(new CustomEvent('budget-data-change'))}
 function adjust(item,patch){save({...budget,adjustments:{...(budget.adjustments||{}),[item.key]:{...((budget.adjustments||{})[item.key]||{}),...patch}}})}
 function deleteOccurrence(item){if(window.confirm(`Remove ${item.name} from this occurrence only?`))adjust(item,{deleted:true})}
 if(mode!=='payday'||!budget)return null;
 return <section className="panel payday-week-panel"><div className="section-head"><div><p className="eyebrow">Payday week view</p><h2>Thursday → Wednesday</h2></div><p>Projected ending bank uses planned bills. A reconciled actual balance becomes the authoritative carry-forward.</p></div><div className="weeks payday-weeks">{weeks.map((w,i)=><article className="week-card" key={w.start}><div className="week-head"><div><p className="eyebrow">Week {i+1}</p><h2>{pretty(w.start)} – {pretty(w.end)}</h2></div><div className="week-net"><small>Projected ending bank</small><strong>{money(w.projected)}</strong></div></div><div className="week-stats"><span>Starting bank <b>{money(w.starting)}</b></span><span>Paycheck income <b>{money(w.income)}</b></span><span>Available cash <b>{money(w.available)}</b></span><span>Planned bills <b>{money(w.planned)}</b></span><span>Actually paid <b>{money(w.paid)}</b></span><span>Projected ending bank <b>{money(w.projected)}</b></span></div>{w.items.length?<div className="mobile-budget-lines">{w.items.map(item=><div className="mobile-budget-line editable-budget-line" key={item.key}><strong className="mobile-bill-title">{item.name}</strong><label><small>Due</small><input type="date" value={item.date} onChange={e=>adjust(item,{date:e.target.value})}/></label><span><small>Category</small><b>{item.category}</b></span><label><small>Planned</small><input type="number" step=".01" value={item.planned} onChange={e=>adjust(item,{planned:Number(e.target.value)})}/></label><label><small>Paid</small><input type="number" step=".01" value={item.actual} onChange={e=>adjust(item,{actual:Number(e.target.value)})}/></label><button type="button" className="small-button budget-line-delete" onClick={()=>deleteOccurrence(item)}>Remove</button></div>)}</div>:<p className="empty">No bills this week.</p>}</article>)}</div></section>;
}
