'use client';

import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
const BUDGET_KEY='my-budget-v5',RECON_KEY='my-budget-reconciliation-v1',VIEW_KEY='my-budget-week-view-v1';
const parse=s=>new Date(`${s}T12:00:00`),iso=d=>d.toISOString().slice(0,10),money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
function addDays(s,n){const d=parse(s);d.setDate(d.getDate()+n);return iso(d)}
function addMonths(s,n){const a=parse(s),day=a.getDate(),d=new Date(a.getFullYear(),a.getMonth()+n,1,12),last=new Date(d.getFullYear(),d.getMonth()+1,0,12).getDate();d.setDate(Math.min(day,last));return iso(d)}
function monthBounds(m){const[y,mo]=m.split('-').map(Number);return{start:`${m}-01`,end:iso(new Date(y,mo,0,12))}}
function weekStart(date,target){const d=parse(date),back=(d.getDay()-target+7)%7;return addDays(date,-back)}
function fullBounds(m,mode){const b=monthBounds(m),target=mode==='payday'?4:1,start=weekStart(b.start,target),last=weekStart(b.end,target);return{start,end:addDays(last,6)}}
function occurrences(b,start,end){let date=b.startDate||b.dueDate,out=[],guard=0,stop=b.endDate||null;if(!date||stop&&date>stop)return[];while(date<start&&guard++<500){if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else return[]}while(date<=end&&(!stop||date<=stop)&&guard++<1000){if(date>=start)out.push({...b,date,key:`${b.id}:${date}`});if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else break}return out}
export default function WeeklyReconciliation(){
 const[budget,setBudget]=useState(null),[recon,setRecon]=useState({}),[month,setMonth]=useState('2026-09'),[mode,setMode]=useState('payday'),[drafts,setDrafts]=useState({}),[targets,setTargets]=useState([]),[expanded,setExpanded]=useState({});
 useEffect(()=>{function load(){try{const raw=localStorage.getItem(BUDGET_KEY);if(raw)setBudget(JSON.parse(raw));const rr=localStorage.getItem(RECON_KEY);if(rr)setRecon(JSON.parse(rr));setMode(localStorage.getItem(VIEW_KEY)||'payday')}catch{}}load();const id=setInterval(load,750);const view=e=>setMode(e.detail||localStorage.getItem(VIEW_KEY)||'payday');window.addEventListener('budget-week-view-change',view);return()=>{clearInterval(id);window.removeEventListener('budget-week-view-change',view)}},[]);
 useEffect(()=>{if(Object.keys(recon).length||localStorage.getItem(RECON_KEY))localStorage.setItem(RECON_KEY,JSON.stringify(recon))},[recon]);
 useEffect(()=>{function sync(){const selector=mode==='payday'?'.payday-weeks .week-card':'.details-wrap .weeks:not(.payday-weeks) .week-card';setTargets([...document.querySelectorAll(selector)]);const input=document.querySelector('.month-nav input[type="month"]');if(input?.value)setMonth(input.value)}sync();const timer=setInterval(sync,500);return()=>clearInterval(timer)},[mode]);
 const weeks=useMemo(()=>{if(!budget)return[];const{start,end}=fullBounds(month,mode),days=Math.round((parse(end)-parse(start))/86400000)+1,out=Array.from({length:Math.ceil(days/7)},(_,i)=>({start:addDays(start,i*7),end:addDays(start,i*7+6),income:0,planned:0,paid:0}));for(const o of (budget.bills||[]).flatMap(b=>occurrences(b,start,end))){const a=(budget.adjustments||{})[o.key]||{};if(a.deleted)continue;const date=a.date||o.date,wi=Math.floor((parse(date)-parse(start))/86400000/7);if(out[wi]){out[wi].planned+=Number(a.planned??o.amount);out[wi].paid+=Number(a.actual||0)}}let pd=budget.payday,guard=0;while(pd&&pd<start&&guard++<100)pd=addDays(pd,14);while(pd&&pd<=end&&guard++<200){const wi=Math.floor((parse(pd)-parse(start))/86400000/7);if(out[wi])out[wi].income+=Number(budget.paycheck||0);pd=addDays(pd,14)}const prior=Object.entries(recon).filter(([k,r])=>k<start&&r?.reconciled&&r.actualBalance!==''&&r.actualBalance!==undefined).sort(([a],[b])=>b.localeCompare(a))[0];let carry=prior?Number(prior[1].actualBalance):Number(budget.bank||0);return out.map((w,i)=>{const key=w.start,r=recon[key]||{},extras=(r.transactions||[]).reduce((s,t)=>s+Number(t.amount||0),0),projected=carry+w.income-w.planned+extras,actualFlow=carry+w.income-w.paid+extras,ending=r.reconciled&&r.actualBalance!==''&&r.actualBalance!==undefined?Number(r.actualBalance):projected,row={...w,key,index:i,starting:carry,extras,projected,actualFlow,ending,reconciliation:r};carry=ending;return row})},[budget,recon,month,mode]);
 useEffect(()=>{targets.forEach((card,i)=>{const archived=!!weeks[i]?.reconciliation?.reconciled;card.classList.toggle('reconciled-archived',archived);card.style.order=archived?String(100+i):String(i)})},[targets,weeks]);
 function patch(key,p){setRecon(r=>({...r,[key]:{...(r[key]||{}),...p}}))}
 function addTransaction(key){const d=drafts[key]||{};if(!d.description||d.amount===''||d.amount===undefined)return;const amount=Number(d.amount);if(Number.isNaN(amount))return;setRecon(r=>({...r,[key]:{...(r[key]||{}),transactions:[...((r[key]||{}).transactions||[]),{id:String(Date.now()),description:d.description,amount}]}}));setDrafts(x=>({...x,[key]:{description:'',amount:''}}))}
 function removeTransaction(key,id){setRecon(r=>({...r,[key]:{...(r[key]||{}),transactions:((r[key]||{}).transactions||[]).filter(t=>t.id!==id)}}))}
 function reconcileWeek(w){const r=recon[w.key]||{};if(r.actualBalance===''||r.actualBalance===undefined){alert('Enter the actual bank balance before reconciling this week.');return}patch(w.key,{reconciled:true,reconciledAt:new Date().toISOString()});setExpanded(x=>({...x,[w.key]:false}))}
 function reopen(w){patch(w.key,{reconciled:false});setExpanded(x=>({...x,[w.key]:true}))}
 function panel(w){const r=w.reconciliation,tx=r.transactions||[],difference=r.actualBalance===''||r.actualBalance===undefined?null:Number(r.actualBalance)-w.actualFlow;if(r.reconciled&&!expanded[w.key])return <div className="reconciliation-panel archived-summary"><div><p className="eyebrow">Reconciled · Archived</p><h3>Week {w.index+1}: {w.start} – {w.end}</h3><small>Actual ending bank balance</small><strong>{money(w.ending)}</strong></div><div className="archive-actions"><button type="button" className="small-button" onClick={()=>setExpanded(x=>({...x,[w.key]:true}))}>View week</button><button type="button" className="small-button" onClick={()=>reopen(w)}>Reopen week</button></div></div>;
 return <div className="reconciliation-panel"><div className="week-head"><div><p className="eyebrow">Reconcile this week{r.reconciled?' · Reconciled':''}</p><h3>Bank reality check</h3></div><div className={w.ending<0?'week-net negative-text':'week-net'}><small>Carry-forward balance</small><strong>{money(w.ending)}</strong></div></div><div className="week-stats"><span>Starting bank <b>{money(w.starting)}</b></span><span>Income <b>{money(w.income)}</b></span><span>Planned bills <b>{money(w.planned)}</b></span><span>Actually paid <b>{money(w.paid)}</b></span><span>Unplanned +/- <b>{money(w.extras)}</b></span><span>Projected ending <b>{money(w.projected)}</b></span><span>Bank based on recorded activity <b>{money(w.actualFlow)}</b></span></div>{tx.length>0&&<div className="table-wrap"><table><thead><tr><th>Unplanned transaction</th><th>Amount</th><th></th></tr></thead><tbody>{tx.map(t=><tr key={t.id}><td>{t.description}</td><td>{money(t.amount)}</td><td><button type="button" className="small-button" onClick={()=>removeTransaction(w.key,t.id)}>Delete</button></td></tr>)}</tbody></table></div>}<div className="form-grid rule-add"><input placeholder="Unplanned payment or credit" value={(drafts[w.key]||{}).description||''} onChange={e=>setDrafts(x=>({...x,[w.key]:{...(x[w.key]||{}),description:e.target.value}}))}/><input type="number" step=".01" placeholder="-50 expense / +50 credit" value={(drafts[w.key]||{}).amount??''} onChange={e=>setDrafts(x=>({...x,[w.key]:{...(x[w.key]||{}),amount:e.target.value}}))}/><button type="button" onClick={()=>addTransaction(w.key)}>Add transaction</button></div><div className="form-grid rule-add"><label>Actual bank balance<input type="number" step=".01" placeholder="Bank balance" value={r.actualBalance??''} disabled={!!r.reconciled} onChange={e=>patch(w.key,{actualBalance:e.target.value})}/></label>{difference!==null&&<div><small>Difference vs recorded activity</small><strong style={{display:'block'}}>{money(difference)}</strong></div>}{r.reconciled?<><button type="button" onClick={()=>setExpanded(x=>({...x,[w.key]:false}))}>Collapse</button><button type="button" onClick={()=>reopen(w)}>Reopen week</button></>:<button type="button" onClick={()=>reconcileWeek(w)}>Reconcile week</button>}</div></div>}
 if(!budget||!targets.length)return null;return <>{weeks.map((w,i)=>targets[i]?createPortal(panel(w),targets[i],w.key):null)}</>;
}
