'use client';

import { useEffect, useMemo, useState } from 'react';

const BUDGET_KEY='my-budget-v5';
const RECON_KEY='my-budget-reconciliation-v1';
const parse=s=>new Date(`${s}T12:00:00`);
const iso=d=>d.toISOString().slice(0,10);
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
function addDays(s,n){const d=parse(s);d.setDate(d.getDate()+n);return iso(d)}
function addMonths(s,n){const a=parse(s),day=a.getDate(),d=new Date(a.getFullYear(),a.getMonth()+n,1,12),last=new Date(d.getFullYear(),d.getMonth()+1,0,12).getDate();d.setDate(Math.min(day,last));return iso(d)}
function monthBounds(m){const[y,mo]=m.split('-').map(Number);return{start:`${m}-01`,end:iso(new Date(y,mo,0,12))}}
function weekIndex(date,start){return Math.floor((parse(date)-parse(start))/86400000/7)}
function occurrences(b,start,end){let date=b.startDate||b.dueDate,out=[],guard=0,stop=b.endDate||null;if(!date||stop&&date>stop)return[];while(date<start&&guard++<500){if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else return[]}while(date<=end&&(!stop||date<=stop)&&guard++<1000){if(date>=start)out.push({...b,date,key:`${b.id}:${date}`});if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else break}return out}

export default function WeeklyReconciliation(){
 const[budget,setBudget]=useState(null),[recon,setRecon]=useState({}),[month,setMonth]=useState('2026-09'),[drafts,setDrafts]=useState({});
 useEffect(()=>{function load(){try{const raw=localStorage.getItem(BUDGET_KEY);if(raw){const next=JSON.parse(raw);setBudget(prev=>JSON.stringify(prev)===JSON.stringify(next)?prev:next)}}catch{}}load();const id=setInterval(load,750);return()=>clearInterval(id)},[]);
 useEffect(()=>{try{const raw=localStorage.getItem(RECON_KEY);if(raw)setRecon(JSON.parse(raw))}catch{}},[]);
 useEffect(()=>{if(Object.keys(recon).length||localStorage.getItem(RECON_KEY))localStorage.setItem(RECON_KEY,JSON.stringify(recon))},[recon]);
 const weeks=useMemo(()=>{if(!budget)return[];const{start,end}=monthBounds(month),days=Math.round((parse(end)-parse(start))/86400000)+1,out=Array.from({length:Math.ceil(days/7)},(_,i)=>({start:addDays(start,i*7),end:addDays(start,Math.min(days-1,i*7+6)),income:0,paid:0}));for(const o of (budget.bills||[]).flatMap(b=>occurrences(b,start,end))){const a=(budget.adjustments||{})[o.key]||{};if(a.deleted)continue;const date=a.date||o.date,wi=a.week!==undefined?Number(a.week):weekIndex(date,start);if(out[wi])out[wi].paid+=Number(a.actual||0)}let pd=budget.payday,guard=0;while(pd&&pd<start&&guard++<100)pd=addDays(pd,14);while(pd&&pd<=end&&guard++<200){const wi=weekIndex(pd,start);if(out[wi])out[wi].income+=Number(budget.paycheck||0);pd=addDays(pd,14)}let carry=Number(budget.bank||0);return out.map((w,i)=>{const key=w.start,r=recon[key]||{},extras=(r.transactions||[]).reduce((s,t)=>s+Number(t.amount||0),0),expected=carry+w.income-w.paid+extras,ending=r.reconciled&&r.actualBalance!==''&&r.actualBalance!==undefined?Number(r.actualBalance):expected,row={...w,key,index:i,starting:carry,extras,expected,ending,reconciliation:r};carry=ending;return row})},[budget,recon,month]);
 function patch(key,patch){setRecon(r=>({...r,[key]:{...(r[key]||{}),...patch}}))}
 function addTransaction(key){const d=drafts[key]||{};if(!d.description||d.amount===''||d.amount===undefined)return;const amount=Number(d.amount);if(Number.isNaN(amount))return;setRecon(r=>({...r,[key]:{...(r[key]||{}),transactions:[...((r[key]||{}).transactions||[]),{id:String(Date.now()),description:d.description,amount}]}}));setDrafts(x=>({...x,[key]:{description:'',amount:''}}))}
 function removeTransaction(key,id){setRecon(r=>({...r,[key]:{...(r[key]||{}),transactions:((r[key]||{}).transactions||[]).filter(t=>t.id!==id)}}))}
 function reconcileWeek(w){const r=recon[w.key]||{};if(r.actualBalance===''||r.actualBalance===undefined){alert('Enter the actual bank balance before reconciling this week.');return}patch(w.key,{reconciled:true,reconciledAt:new Date().toISOString()})}
 if(!budget)return null;
 return <section className="panel" style={{margin:'24px auto',maxWidth:1200}}><div className="section-head"><div><p className="eyebrow">Reality check</p><h2>Weekly reconciliation</h2></div><div><label>Month <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div></div><p className="sub">Record unexpected money in or out, enter what your bank actually shows, then reconcile the week. A reconciled ending balance becomes the next week’s starting bank balance. Your planned bills and recurring rules are not changed.</p><div className="weeks">{weeks.map(w=>{const r=w.reconciliation,tx=r.transactions||[],difference=r.actualBalance===''||r.actualBalance===undefined?null:Number(r.actualBalance)-w.expected;return <article className="week-card" key={w.key}><div className="week-head"><div><p className="eyebrow">Week {w.index+1}{r.reconciled?' · Reconciled':''}</p><h2>{w.start} – {w.end}</h2></div><div className={w.ending<0?'week-net negative-text':'week-net'}><small>What's left in the bank</small><strong>{money(w.ending)}</strong></div></div><div className="week-stats"><span>Starting bank <b>{money(w.starting)}</b></span><span>Income <b>{money(w.income)}</b></span><span>Recorded payments <b>{money(w.paid)}</b></span><span>Unplanned +/- <b>{money(w.extras)}</b></span><span>Expected bank <b>{money(w.expected)}</b></span></div>{tx.length>0&&<div className="table-wrap"><table><thead><tr><th>Unplanned transaction</th><th>Amount</th><th></th></tr></thead><tbody>{tx.map(t=><tr key={t.id}><td>{t.description}</td><td>{money(t.amount)}</td><td><button type="button" className="small-button" onClick={()=>removeTransaction(w.key,t.id)}>Delete</button></td></tr>)}</tbody></table></div>}<div className="form-grid rule-add"><input placeholder="Unplanned payment or credit" value={(drafts[w.key]||{}).description||''} onChange={e=>setDrafts(x=>({...x,[w.key]:{...(x[w.key]||{}),description:e.target.value}}))}/><input type="number" step=".01" placeholder="-50 expense / +50 credit" value={(drafts[w.key]||{}).amount??''} onChange={e=>setDrafts(x=>({...x,[w.key]:{...(x[w.key]||{}),amount:e.target.value}}))}/><button type="button" onClick={()=>addTransaction(w.key)}>Add transaction</button></div><div className="form-grid rule-add"><label>Actual bank balance<input type="number" step=".01" placeholder="Bank balance" value={r.actualBalance??''} disabled={!!r.reconciled} onChange={e=>patch(w.key,{actualBalance:e.target.value})}/></label>{difference!==null&&<div><small>Difference from expected</small><strong style={{display:'block'}}>{money(difference)}</strong></div>}{r.reconciled?<button type="button" onClick={()=>patch(w.key,{reconciled:false})}>Reopen week</button>:<button type="button" onClick={()=>reconcileWeek(w)}>Reconcile week</button>}</div></article>})}</div></section>
}
