'use client';

import { useEffect, useMemo, useState } from 'react';

const BUDGET_KEY='my-budget-v5';
const VIEW_KEY='my-budget-week-view-v1';
const parse=s=>new Date(`${s}T12:00:00`);
const iso=d=>d.toISOString().slice(0,10);
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
function addDays(s,n){const d=parse(s);d.setDate(d.getDate()+n);return iso(d)}
function addMonths(s,n){const a=parse(s),day=a.getDate(),d=new Date(a.getFullYear(),a.getMonth()+n,1,12),last=new Date(d.getFullYear(),d.getMonth()+1,0,12).getDate();d.setDate(Math.min(day,last));return iso(d)}
function pretty(s){return parse(s).toLocaleDateString('en-US',{month:'short',day:'numeric'})}
function occurrences(b,start,end){let date=b.startDate||b.dueDate,out=[],guard=0,stop=b.endDate||null;if(!date||stop&&date>stop)return[];while(date<start&&guard++<500){if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else return[]}while(date<=end&&(!stop||date<=stop)&&guard++<1000){if(date>=start)out.push({...b,date,key:`${b.id}:${date}`});if(b.repeat==='weekly')date=addDays(date,7);else if(b.repeat==='biweekly')date=addDays(date,14);else if(b.repeat==='monthly')date=addMonths(date,1);else break}return out}
function weekStartFor(date,mode){const d=parse(date),target=mode==='payday'?4:1,back=(d.getDay()-target+7)%7;return addDays(date,-back)}
function monthBounds(m){const[y,mo]=m.split('-').map(Number);return{start:`${m}-01`,end:iso(new Date(y,mo,0,12))}}
function inferCategory(name=''){const n=name.toLowerCase();if(n.includes('rent'))return'Housing';if(n.includes('bronco')||n.includes('gas')||n.includes('auto'))return'Auto/Transportation';if(n.includes('grocery')||n.includes('household'))return'Food/Household';if(n.includes('internet')||n.includes('phone')||n.includes('spectrum')||n.includes('village'))return'Utilities';if(n.includes('support'))return'Child Support';if(n.includes('zip')||n.includes('advance'))return'Debt/Financing';if(n.includes('insurance')||n.includes('geico'))return'Insurance';if(n.includes('tax'))return'Taxes';return'Other'}

export default function WeekViewController(){
 const[mode,setMode]=useState('payday'),[budget,setBudget]=useState(null),[month,setMonth]=useState('2026-09');
 useEffect(()=>{setMode(localStorage.getItem(VIEW_KEY)||'payday');function view(e){setMode(e.detail||localStorage.getItem(VIEW_KEY)||'payday')}window.addEventListener('budget-week-view-change',view);return()=>window.removeEventListener('budget-week-view-change',view)},[]);
 useEffect(()=>{function load(){try{const raw=localStorage.getItem(BUDGET_KEY);if(raw)setBudget(JSON.parse(raw));const input=document.querySelector('.month-nav input[type="month"]');if(input?.value)setMonth(input.value)}catch{}}load();const id=setInterval(load,750);return()=>clearInterval(id)},[]);
 useEffect(()=>{const original=document.querySelector('.details-wrap .weeks');if(original)original.classList.toggle('week-view-hidden',mode==='payday');return()=>original?.classList.remove('week-view-hidden')},[mode,budget,month]);
 const weeks=useMemo(()=>{if(!budget||mode!=='payday')return[];const bounds=monthBounds(month),start=weekStartFor(bounds.start,'payday'),lastStart=weekStartFor(bounds.end,'payday'),end=addDays(lastStart,6),count=Math.round((parse(end)-parse(start))/86400000/7)+1,out=Array.from({length:count},(_,i)=>({start:addDays(start,i*7),end:addDays(start,i*7+6),items:[],income:0}));for(const o of (budget.bills||[]).flatMap(b=>occurrences(b,start,end))){const a=(budget.adjustments||{})[o.key]||{};if(a.deleted)continue;const date=a.date||o.date,idx=Math.floor((parse(date)-parse(start))/86400000/7);if(out[idx])out[idx].items.push({...o,date,category:o.category||inferCategory(o.name),planned:Number(a.planned??o.amount),actual:Number(a.actual??0)})}let pd=budget.payday,guard=0;while(pd&&pd<start&&guard++<100)pd=addDays(pd,14);while(pd&&pd<=end&&guard++<200){const idx=Math.floor((parse(pd)-parse(start))/86400000/7);if(out[idx])out[idx].income+=Number(budget.paycheck||0);pd=addDays(pd,14)}out.forEach(w=>w.items.sort((a,b)=>a.date.localeCompare(b.date)));return out},[budget,month,mode]);
 if(mode!=='payday'||!budget)return null;
 return <section className="panel payday-week-panel"><div className="section-head"><div><p className="eyebrow">Payday week view</p><h2>Thursday → Wednesday</h2></div><p>Bills are grouped around your Thursday payday. Change this anytime under Budget setup.</p></div><div className="weeks payday-weeks">{weeks.map((w,i)=>{const planned=w.items.reduce((s,x)=>s+x.planned,0),actual=w.items.reduce((s,x)=>s+x.actual,0);return <article className="week-card" key={w.start}><div className="week-head"><div><p className="eyebrow">Week {i+1}</p><h2>{pretty(w.start)} – {pretty(w.end)}</h2></div><div className="week-net"><small>Income / planned</small><strong>{money(w.income)} / {money(planned)}</strong></div></div><div className="week-stats"><span>Income <b>{money(w.income)}</b></span><span>Planned <b>{money(planned)}</b></span><span>Paid <b>{money(actual)}</b></span></div>{w.items.length?<div className="mobile-budget-lines">{w.items.map(item=><div className="mobile-budget-line" key={item.key}><strong className="mobile-bill-title">{item.name}</strong><span><small>Due</small><b>{pretty(item.date)}</b></span><span><small>Category</small><b>{item.category}</b></span><span><small>Planned</small><b>{money(item.planned)}</b></span><span><small>Paid</small><b>{money(item.actual)}</b></span></div>)}</div>:<p className="empty">No bills this week.</p>}</article>})}</div></section>;
}
